package com.example.mycity.datasource

import android.annotation.SuppressLint
import com.example.mycity.R
import com.example.mycity.model.Category
import com.example.mycity.model.Recommendation

object dataSource {

    @SuppressLint("ResourceType")
    val cityCatories = listOf<Category>(
        Category(
            R.string.category_1, R.drawable.image1, listOf<Recommendation>(
                Recommendation(
                    R.string.category_1_recommendation_1,
                    R.string.category_1_recommendation_1_details,
                    R.drawable.image1
                ),
                Recommendation(
                    R.string.category_1_recommendation_2,
                    R.string.category_1_recommendation_2_details,
                    R.drawable.image1
                ),
                Recommendation(
                    R.string.category_1_recommendation_3,
                    R.string.category_1_recommendation_3_details,
                    R.drawable.image1
                ),
                Recommendation(
                    R.string.category_1_recommendation_4,
                    R.string.category_1_recommendation_4_details,
                    R.drawable.image1
                ),
                Recommendation(
                    R.string.category_1_recommendation_5,
                    R.string.category_1_recommendation_5_details,
                    R.drawable.image1
                ),
                Recommendation(
                    R.string.category_1_recommendation_6,
                    R.string.category_1_recommendation_6_details,
                    R.drawable.image1
                ),
            )
        ),
        Category(
            R.string.category_2, R.drawable.image2, listOf<Recommendation>(
                Recommendation(
                    R.string.category_2_recommendation_1,
                    R.string.category_2_recommendation_1_details,
                    R.drawable.image2
                ),
                Recommendation(
                    R.string.category_2_recommendation_2,
                    R.string.category_2_recommendation_2_details,
                    R.drawable.image2
                ),
                Recommendation(
                    R.string.category_2_recommendation_3,
                    R.string.category_2_recommendation_3_details,
                    R.drawable.image2
                ),
                Recommendation(
                    R.string.category_2_recommendation_4,
                    R.string.category_2_recommendation_4_details,
                    R.drawable.image2
                ),
                Recommendation(
                    R.string.category_2_recommendation_5,
                    R.string.category_2_recommendation_5_details,
                    R.drawable.image2
                ),
                Recommendation(
                    R.string.category_2_recommendation_6,
                    R.string.category_2_recommendation_6_details,
                    R.drawable.image2
                ),
            )
        ),
        Category(
            R.string.category_3, R.drawable.image3, listOf<Recommendation>(
                Recommendation(
                    R.string.category_3_recommendation_1,
                    R.string.category_3_recommendation_1_details,
                    R.drawable.image3
                ),
                Recommendation(
                    R.string.category_3_recommendation_2,
                    R.string.category_3_recommendation_2_details,
                    R.drawable.image3
                ),
                Recommendation(
                    R.string.category_3_recommendation_3,
                    R.string.category_3_recommendation_3_details,
                    R.drawable.image3
                ),
                Recommendation(
                    R.string.category_3_recommendation_4,
                    R.string.category_3_recommendation_4_details,
                    R.drawable.image3
                ),
                Recommendation(
                    R.string.category_3_recommendation_5,
                    R.string.category_3_recommendation_5_details,
                    R.drawable.image3
                ),
                Recommendation(
                    R.string.category_3_recommendation_6,
                    R.string.category_3_recommendation_6_details,
                    R.drawable.image3
                ),
            )
        ),
        Category(
            R.string.category_4, R.drawable.image4, listOf<Recommendation>(
                Recommendation(
                    R.string.category_4_recommendation_1,
                    R.string.category_4_recommendation_1_details,
                    R.drawable.image4
                ),
                Recommendation(
                    R.string.category_4_recommendation_2,
                    R.string.category_4_recommendation_2_details,
                    R.drawable.image4
                ),
                Recommendation(
                    R.string.category_4_recommendation_3,
                    R.string.category_4_recommendation_3_details,
                    R.drawable.image4
                ),
                Recommendation(
                    R.string.category_4_recommendation_4,
                    R.string.category_4_recommendation_4_details,
                    R.drawable.image4
                ),
                Recommendation(
                    R.string.category_4_recommendation_5,
                    R.string.category_4_recommendation_5_details,
                    R.drawable.image4
                ),
                Recommendation(
                    R.string.category_4_recommendation_6,
                    R.string.category_4_recommendation_6_details,
                    R.drawable.image4
                ),
            )
        ),
        Category(
            R.string.category_5, R.drawable.image5, listOf<Recommendation>(
                Recommendation(
                    R.string.category_5_recommendation_1,
                    R.string.category_5_recommendation_1_details,
                    R.drawable.image5
                ),
                Recommendation(
                    R.string.category_5_recommendation_2,
                    R.string.category_5_recommendation_2_details,
                    R.drawable.image5
                ),
                Recommendation(
                    R.string.category_5_recommendation_3,
                    R.string.category_5_recommendation_3_details,
                    R.drawable.image5
                ),
                Recommendation(
                    R.string.category_5_recommendation_4,
                    R.string.category_5_recommendation_4_details,
                    R.drawable.image5
                ),
                Recommendation(
                    R.string.category_5_recommendation_5,
                    R.string.category_5_recommendation_5_details,
                    R.drawable.image5
                ),
                Recommendation(
                    R.string.category_5_recommendation_6,
                    R.string.category_5_recommendation_6_details,
                    R.drawable.image5
                ),
            )
        ),
        Category(
            R.string.category_6, R.drawable.image6, listOf<Recommendation>(
                Recommendation(
                    R.string.category_6_recommendation_1,
                    R.string.category_6_recommendation_1_details,
                    R.drawable.image6
                ),
                Recommendation(
                    R.string.category_6_recommendation_2,
                    R.string.category_6_recommendation_2_details,
                    R.drawable.image6
                ),
                Recommendation(
                    R.string.category_6_recommendation_3,
                    R.string.category_6_recommendation_3_details,
                    R.drawable.image6
                ),
                Recommendation(
                    R.string.category_6_recommendation_4,
                    R.string.category_6_recommendation_4_details,
                    R.drawable.image6
                ),
                Recommendation(
                    R.string.category_6_recommendation_5,
                    R.string.category_6_recommendation_5_details,
                    R.drawable.image6
                ),
                Recommendation(
                    R.string.category_6_recommendation_6,
                    R.string.category_6_recommendation_6_details,
                    R.drawable.image6
                ),
            )
        )
    )
}